# Generation of Kubernetes YAML is still under development!
#
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.2.3
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-08-20T20:48:44Z"
  labels:
    app: tmc-wiki-pod
  name: tmc-wiki-pod
spec:
  containers:
  - args:
    - postgres
    command:
    - docker-entrypoint.sh
    env:
    - name: PATH
      value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin
    - name: TERM
      value: xterm
    - name: container
      value: podman
    - name: LANG
      value: en_US.utf8
    - name: PG_MAJOR
      value: "13"
    - name: PG_VERSION
      value: 13.3-1.pgdg100+1
    - name: PGDATA
      value: /var/lib/postgresql/data
    - name: GOSU_VERSION
      value: "1.12"
    - name: POSTGRES_USER
      value: user
    - name: POSTGRES_DB
      value: wiki
    - name: POSTGRES_PASSWORD
      value: pass
    image: docker.io/library/postgres:latest
    name: postgres-wiki
    ports:
    - containerPort: 5432
      hostPort: 5432
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    tty: true
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: pgdata-pvc
    workingDir: /
  dnsConfig: {}
  restartPolicy: Never
  volumes:
  - name: pgdata-pvc
    persistentVolumeClaim:
      claimName: pgdata
status: {}

